version = 1.0.3
author = Nick Haghiri
authorMail = ns.haghiri@gmail.com
homepageUrl = https://github.com/ElCruncharino/neostego
jdkDocsUrl = https://docs.oracle.com/en/java/javase/21/docs/api/

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Build performance
org.gradle.jvmargs=-Xmx2560m
